### PR TITLE
Cart page and cart database

### PR DESCRIPTION
**Pull request by KUchuna**
- Created new "Cart" data table on postgress;
- Added "Add to cart" button on products cards;
- Added cart icon showing current total items added to cart;
- Added simple cart page;
- Added products cart adding functionality.

### CODE REVIEW

**Comment by KUchuna** [comment]
Please review my code,

yours faithfully,
Ucha

@anikobakhidze @mariamkhutuashvili @GeorgeTch

**Comment by anikobakhidze** [comment]
Thanks Ucha,
Everything works properly, you can merge

**Comment by GeorgeTch** [comment]
everything looks perfect for me 👌

**Comment by mariamkhutuashvili** [comment]
Everything looks good to me. I agree to merge this pull request. Great work!

**Pull request merged**
